export const authApi = {
  signup: "/auth-service/sign-up",
  signin: "/auth-service/sign-in",
  validateOTP: "/auth-service/validate-otp",
  googleConnect: "/auth-service/google-oauth2/signup-connect",
  googleAuthorize: "/auth-service/google-oauth2/signup-authorize",
  googleSignup: "/auth-service/google-oauth2/sign-up",
  googleSigninConnect: "/auth-service/google-oauth2/signin-connect",
  googleSigninAuthorize: "/auth-service/google-oauth2/signin-authorize",
  microsoftConnect: "/auth-service/microsoft-oauth2/signup-connect",
  microsoftAuthorize: "/auth-service/microsoft-oauth2/signup-authorize",
  microsoftSignup: "/auth-service/microsoft-oauth2/sign-up",
  microsoftSigninConnect: "/auth-service/microsoft-oauth2/signin-connect",
  microsoftSigninAuthorize: "/auth-service/microsoft-oauth2/signin-authorize",
  unlockAccount: "/auth-service/unlock-user-account",
  forgotPassword: "/auth-service/forgot-password/initiate",
  resetPassword: "/auth-service/forgot-password/conclude",
};
