#!/bin/bash
set -e

BASE_VERSION=$1


if [[ -z "${CODEBUILD_RESOLVED_SOURCE_VERSION}" ]]; then
  GIT_REVISION=`git rev-parse --short=8 HEAD`
else
  GIT_REVISION=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}
fi

CURRENT_TIMESTAMP=`date "+%Y%m%d%H%M%S"`
RELEASE_NUMBER=${CURRENT_TIMESTAMP}.${GIT_REVISION}
APP_VERSION=${BASE_VERSION}-${RELEASE_NUMBER}

echo $APP_VERSION